# Generated by Django 2.0.2 on 2018-03-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20180327_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='short_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
