# Generated by Django 2.0.2 on 2018-03-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180304_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserRole'),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='slug',
            field=models.SlugField(default='barry'),
            preserve_default=False,
        ),
    ]
