# Generated by Django 2.0.2 on 2018-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180304_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
