# Generated by Django 2.0.2 on 2018-03-07 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180307_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
