# Generated by Django 2.0.2 on 2018-03-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180307_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
