# Generated by Django 2.0.2 on 2018-03-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20180313_1740'),
        ('users', '0009_defaultuser_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultuser',
            name='organization',
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.Company'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='assets',
            field=models.ManyToManyField(related_name='users', to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.UserRole'),
        ),
    ]
