# Generated by Django 2.0.2 on 2018-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180314_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='assets',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='assets.Asset'),
        ),
    ]
