# Generated by Django 2.0.2 on 2018-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180314_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='assets',
            field=models.ManyToManyField(related_name='users', to='assets.Asset'),
        ),
    ]
