# Generated by Django 2.0.2 on 2018-03-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180319_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='receiveemails',
            field=models.BooleanField(default=False),
        ),
    ]
