# Generated by Django 2.0.2 on 2018-03-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='slug',
            field=models.SlugField(default='name'),
            preserve_default=False,
        ),
    ]
