# Generated by Django 2.0.2 on 2018-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180307_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
