# Generated by Django 2.0.2 on 2018-03-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assettype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Company'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
