# Generated by Django 2.0.2 on 2018-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180313_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
