# Generated by Django 2.0.2 on 2018-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180326_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
