# Generated by Django 2.0.2 on 2018-03-26 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180326_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetusers',
            field=models.ManyToManyField(blank=True, null=True, through='assets.AssetUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
