# Generated by Django 2.0.2 on 2018-03-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180326_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetuser',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assetusers',
        ),
        migrations.DeleteModel(
            name='AssetUser',
        ),
    ]
