# Generated by Django 2.0.2 on 2018-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20180326_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='verbosevalue',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
