# Generated by Django 2.0.2 on 2018-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
