# Generated by Django 2.0.2 on 2018-03-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatus',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuetype',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
    ]
