# Generated by Django 2.0.2 on 2018-03-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20180306_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatus',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
