# Generated by Django 2.0.2 on 2018-03-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20180307_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
