# Generated by Django 2.0.2 on 2018-03-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20180307_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
