# Generated by Django 2.0.2 on 2018-03-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20180314_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='currentowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
