# Generated by Django 2.0.2 on 2018-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20180314_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
