# Generated by Django 2.0.2 on 2018-03-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20180322_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
