# Generated by Django 2.0.2 on 2018-03-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_address_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='toromont'),
            preserve_default=False,
        ),
    ]
