# Generated by Django 2.0.2 on 2018-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20180313_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
