# Generated by Django 2.0.2 on 2018-03-27 20:19

import apps.files.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20180327_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=apps.files.models.upload_to)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='attachment',
            field=models.FileField(upload_to=apps.files.models.upload_to),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='files.File'),
        ),
    ]
