# Generated by Django 2.0.2 on 2018-03-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20180327_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
