# Generated by Django 2.0.2 on 2018-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_fileattachment_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
